// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqpzJKZOobOnByJ5FcbdPpsy2dxjqU-3s',
    appId: '1:35175200574:web:0b7cf325ff2bed350cde6f',
    messagingSenderId: '35175200574',
    projectId: 'scocar-bd398',
    authDomain: 'scocar-bd398.firebaseapp.com',
    storageBucket: 'scocar-bd398.firebasestorage.app',
    measurementId: 'G-6Y16R3FSZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdAjRRBSG4J45CNRfVPwdgCH11W17SJ28',
    appId: '1:35175200574:android:3c233ed0ad0be8820cde6f',
    messagingSenderId: '35175200574',
    projectId: 'scocar-bd398',
    storageBucket: 'scocar-bd398.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtEm25C3HJg5cuQGP-AkAKJAY1Y1VU13M',
    appId: '1:35175200574:ios:06dbfb973fc81a1c0cde6f',
    messagingSenderId: '35175200574',
    projectId: 'scocar-bd398',
    storageBucket: 'scocar-bd398.firebasestorage.app',
    iosBundleId: 'com.example.scocar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtEm25C3HJg5cuQGP-AkAKJAY1Y1VU13M',
    appId: '1:35175200574:ios:06dbfb973fc81a1c0cde6f',
    messagingSenderId: '35175200574',
    projectId: 'scocar-bd398',
    storageBucket: 'scocar-bd398.firebasestorage.app',
    iosBundleId: 'com.example.scocar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqpzJKZOobOnByJ5FcbdPpsy2dxjqU-3s',
    appId: '1:35175200574:web:248f09b83014fbce0cde6f',
    messagingSenderId: '35175200574',
    projectId: 'scocar-bd398',
    authDomain: 'scocar-bd398.firebaseapp.com',
    storageBucket: 'scocar-bd398.firebasestorage.app',
    measurementId: 'G-43250Q8N48',
  );
}
